version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=mydb
      - DB_POSTGRESDB_USER=user
      - DB_POSTGRESDB_PASSWORD=password
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=securepass
      - N8N_HOST=localhost
      - N8N_PORT=5678
    depends_on:
      - postgres

  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"

  langchain-server:
    build: ./langchain-server
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./langchain-server:/usr/src/app

volumes:
  pgdata:
